/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.OrderController;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import restaurant.MyOrderDB;
import restaurant.ShowDB;


/**
 *
 * @author STUDY fuckin HARD
 */
public class PanelDB extends javax.swing.JPanel {
    private MainGUI mg;
    private ShowDB show;
    private OrderController ordc;
    
    //table
    private Object[] row_table, column_table;
    private DefaultTableModel model;
    /**
     * Creates new form PanelDB
     */
    public PanelDB() {
        initComponents();
        //graph panel and set layout
        GridBagLayout layout = new GridBagLayout();
        graphPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        //get graph
        ordc = new OrderController();;
        show = new ShowDB();
        show.setMyoDB(ordc.getDataDB()); //get data from databasse then set to this array list
        graphPanel.add(show.getGraph(show.getPricePerDay()), c);
        
        //table
        column_table = new Object[4];
        row_table = new Object[4];
        column_table[0] = "Order ID";
        column_table[1] = "Price include vat";
        column_table[2] = "Order Date";
        column_table[3] = "User";

        model = new DefaultTableModel();
        model.setColumnIdentifiers(column_table);
        jTableDB.setModel(model);
        ArrayList<MyOrderDB> myoDB = ordc.getDataDB();
        for(int i=0; i<myoDB.size(); i++){
            row_table[0] = myoDB.get(i).getOrderID();
            row_table[1] = myoDB.get(i).getPrice_include_vat();
            row_table[2] = myoDB.get(i).getDate();
            row_table[3] = myoDB.get(i).getUser();
            model.addRow(row_table);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDB = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        graphPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1143, 616));

        jScrollPane1.setBorder(null);

        jTableDB.setBackground(new java.awt.Color(255, 255, 204));
        jTableDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDB);
        jTableDB.getTableHeader().setReorderingAllowed(false);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDB;
    // End of variables declaration//GEN-END:variables
}
