/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.OrderController;
import gui.MainGUI;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import restaurant.ShowDB;


/**
 *
 * @author STUDY fuckin HARD
 */
public class PanelDB extends javax.swing.JPanel {
    private MainGUI mg;
    ShowDB show;
    OrderController ordc;
    /**
     * Creates new form PanelDB
     */
    public PanelDB(MainGUI mg) {
        initComponents();
        this.mg = mg;
        GridBagLayout layout = new GridBagLayout();
        this.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        ordc = new OrderController();;
        show = new ShowDB();
        show.setMyoDB(ordc.getDataDB()); //get data from databasse then set to this array list
        this.add(show.getGraph(show.getPricePerDay()), c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1143, 616));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
